[package]
name = "dnd_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
rand = "0.8.5"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
roll = { path = "./roll"}
